spring:
  lifecycle:
    timeout-per-shutdown-phase: 60
  mvc:
    servlet:
      load-on-startup: 1
    async:
      request-timeout: 10000
    format:
      time: HH:mm:ss
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  web:
    resources:
      add-mappings: true
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:/workspace/www/static
    #locale: zh_CN
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    #time-zone: GMT+8